<body>
    <!--Main Navigation-->
    <header>
        <!-- Jumbotron -->
        <div class="p-3 text-center bg-white">
            <div class="container">
                <div class="row gy-3">
                    <!-- Left elements -->
                    <div class="col-lg-2 col-sm-4 col-4">
                        <b style="font-size: 2em; margin-right: 30px; color:blue">Music Box</b>
                    </div>
                    <!-- Left elements -->

                    <!-- Center elements -->
                    <div class="order-lg-last col-lg-10 col-sm-8 col-8">
                        <div class="d-flex float-end">
                            <a href="index/token"
                            class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center">
                                <i class="fas fa-shopping-cart m-1 me-md-2"></i>
                                <p class="d-none d-md-block mb-0">Dashboard</p>
                            </a>
                            <a href="/data"
                            class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center">
                                <i class="fas fa-shopping-cart m-1 me-md-2"></i>
                                <p class="d-none d-md-block mb-0">My Saves</p>
                            </a>
                        </div>
                    </div>
                    <!-- Center elements -->

                    <!-- Right elements -->
                </div>
            </div>
        </div>
        <!-- Jumbotron -->
    </header>

    <?php echo $this->tag->form("display"); ?>
    <p>
        <label for="name">Search: </label>
        <input class="form-control" type="text" name="search">
    </p>
    <p>
        <label for="album" class="mx-4">Album :
            <input type="checkbox" name="album" value="albums">
        </label>
        <label for="artist" class="mx-4">Artist :
            <input type="checkbox" name="artist" value="artists">
        </label>
        <label for="playlist" class="mx-4">Playlist :
            <input type="checkbox" name="playlist" value="playlists">
        </label>
        <label for="track" class="mx-4">Track :
            <input type="checkbox" name="track" value="tracks">
        </label>
        <label for="show" class="mx-4">Show :
            <input type="checkbox" name="show" value="shows">
        </label>
        <label for="episode" class="mx-4">Episode :
            <input type="checkbox" name="episode" value="episodes">
        </label>
    </p>
    <?php echo $this->tag->submitButton(["Submit", 'class' => 'col-3 btn btn-primary']); ?>
    </form>

    <section>
        <div class="container my-5">
            <header class="mb-4">
                <h3>Dashboard</h3>
            </header>
            <div class="row" id="main_display">
                <?php
                echo $recommend;
                ?>
            </div>
        </div>
    </section>

</body>